### ISSUE TITLE
ruvector@0.2.23: data-plane broken — VectorDB CRUD, GNN, attention, embed, rvf, benchmark all fail

### ISSUE THREAD

**Issue by ronmikailov** [ruvnet/ruvector#402]
## Summary

After exhaustive testing of every top-level subcommand in `ruvector@0.2.23`, **the core data plane is non-functional**. Failures cluster into 3 root causes, all in scope of the existing release-hygiene tracker (#399, #400, #401):

- **A. `VectorDB` API drift** — CLI calls methods that no longer exist on `@ruvector/core`'s native binding.
- **B. GNN / attention N-API binding errors** — typed-array marshalling broken across all GNN ops.
- **C. More missing `dist/` paths** — beyond #399, the CLI also requires `dist/core/onnx-embedder.js` and `dist/core/rvf-wrapper.js`.

CLI-parser, help text, info/status commands, and a few utility commands (decompile, mcp tools, llm embed, identity, brain) are all healthy — so the CLI shell is fine, the binding integration is what's broken.

---

## A. `VectorDB` API drift — entire CRUD lifecycle blocked

The CLI assumes a `VectorDB` API surface (`insertBatch`, on-disk persistence) that doesn't match what `@ruvector/core@0.1.31` actually ships.

### A1. `create` claims success but writes no file

```bash
$ ruvector create -d 4 ./test.db
- Creating database...
✔ Database created: ./test.db
  Dimension: 4
  Metric: cosine
  Implementation: native (@ruvector/core)

$ ls test.db
ls: cannot access 'test.db': No such file or directory   # <-- nothing on disk
```

The "✔" success line is printed but no file is created. Every downstream read/write then fails with `ENOENT`.

### A2. `insert` calls a missing method

```bash
$ ruvector insert ./test.db ./vecs.json
✖ Failed to insert vectors
db.insertBatch is not a function
```

`db.insertBatch` doesn't exist on the current `VectorDB` binding. Same root cause causes:

- `ruvector demo --basic` → `db.insert is not a function` (related — different method, same drift, see #400)
- `ruvector benchmark` → `db.insertBatch is not a function` (same as above)

### A3. `stats` / `search` / `export` / `import` are all blocked

All fail with `ENOENT` because `create` doesn't actually persist. So even before hitting any API drift, the file simply isn't there. After one round-trip, **the entire VectorDB CLI workflow is unusable**.

### Likely fix

Audit the CLI handlers in `bin/cli.js` against the current `@ruvector/core` surface. Either:
- Wire the CLI to whatever the actual method names are now (`add`, `addBatch`, etc.), or
- Restore `insertBatch` / persistence on `@ruvector/core` if it was an unintentional regression.

---

## B. GNN + attention N-API errors — every operation crashes

Every meaningful op in the `gnn` and `attention` subsystems crashes:

```bash
$ ruvector gnn layer -i 8 -h 16 --test
✔ GNN Layer created
- Running test forward pass...
✖ Failed to create GNN layer
Get TypedArray info failed

$ ruvector gnn search -q "[0.1,0.2,0.3,0.4]" -c ./cands.json -k 2
✖ Failed to run search
Get TypedArray info failed

$ ruvector gnn compress -f ./cands.json
✖ Failed to compress embeddings
Get TypedArray info failed

$ ruvector attention compute -q "[0.1,0.2,0.3,0.4]" -k ./cands.json
✖ Failed to compute attention
Failed to convert napi value Undefined into rust type \`u32\`
```

`Get TypedArray info failed` is `napi-rs`'s error when a value passed across the FFI boundary isn't actually a typed array. The CLI is likely passing plain `number[]` arrays where the Rust binding expects `Float32Array` / `Float64Array`. The `attention compute` failure (`Undefined into u32`) is the same shape — a missing/malformed scalar arg.

Same root cause as `ruvector demo --gnn` (see #400).

### Likely fix

In the `gnn` and `attention` handlers, convert JS arrays to `Float32Array` (or whatever dtype the binding expects) before crossing the FFI boundary. Add explicit shape/dtype validation up front so the user gets a friendlier error than \`Get TypedArray info failed\`.

---

## C. More missing \`dist/\` paths (extends #399)

In addition to the missing top-level \`dist/index.js\` reported in #399, the CLI also requires:

```bash
$ ruvector embed text "hello world"
Embedding failed: Cannot find module '../dist/core/onnx-embedder.js'

$ ruvector rvf status /path/to/store.rvf
Cannot find module '../dist/core/rvf-wrapper.js'
$ ruvector rvf segments /path/to/store.rvf
Cannot find module '../dist/core/rvf-wrapper.js'
$ ruvector rvf create -d 4 ./test.rvf
Cannot find module '../dist/core/rvf-wrapper.js'
```

So **the entire \`embed\` and \`rvf\` subsystems are blocked** for the same reason as \`doctor\` was in #399 — the build artifact under \`dist/\` is missing from the published tarball. \`prepublishOnly\` runs \`tsc\`, so either the build is failing silently or the \`files\` allowlist isn't matching.

This extends #399 from a doctor-only false negative into "5+ subsystems blocked."

---

## D. What works (so the picture isn't all bleak)

These commands run cleanly with sensible output:

- All 33 \`<cmd> --help\` invocations (CLI parser is fine).
- \`info\`, \`setup\`, \`doctor\` (after #399 shim).
- \`mcp info\`, \`mcp test\` (97 tools registered), \`mcp tools\` (full list).
- \`identity show\`, \`brain status\`, \`edge status\`.
- \`llm info\`, \`llm models\` (3 models listed), \`llm embed\` (returns dimensions, though all-zero output suggests the model isn't actually loaded — separate finding worth investigating).
- \`sona info\`, \`sona status\`, \`sona stats\`, \`sona patterns <q>\` (graceful empty result).
- \`route classify\` (graceful "no routes" message).
- \`gnn info\`, \`attention info\`, \`attention list\`, \`graph --info\`, \`router --info\`, \`cluster --info\` (info commands all work).
- \`hooks stats\`, \`workers stats/triggers/presets/phases\`, \`native list\`, \`rvf examples\` (45 example files listed).
- \`decompile chalk\` (real decompile, writes \`decompiled/chalk@5.6.2/\`, witness root computed) — actually impressive!

---

## Suggested CI / release gate

Combining suggestions across #399, #400, #401, and this issue:

1. **Smoke test every top-level command on a fresh global install:**
   - \`<cmd> --help\` exits 0 (already passes).
   - Safe info subcommand of each grouped command exits 0 (would have caught \`embed text\`, \`rvf status\`, \`optimize\` failures).
2. **Round-trip CRUD test:** \`create → insert → stats → search → export → import\` against a tiny fixture. Would have caught the \`create\` no-file regression and the \`insertBatch\` API drift in one stroke.
3. **GNN/attention shape test:** one fixture forward pass per binding. Would have caught the typed-array marshalling regression.
4. **\`files\` allowlist audit:** make sure every path \`bin/cli.js\` \`require\`s lives under a \`files\` entry. Would have caught all the \`Cannot find module '../dist/...'\` failures (#399 + this issue's section C + #401).

---

## Environment

- ruvector: 0.2.23
- @ruvector/core: 0.1.31
- @ruvector/gnn: 0.1.x (whatever \`ruvector install gnn\` resolves)
- @ruvector/attention: included with core
- @ruvector/graph-node: latest
- @ruvector/router: 0.1.30
- ruvector-extensions: latest
- @ruvector/agentic-synth: latest
- Node.js: v20.19.6
- npm: 10.8.2
- OS: Linux x64 (WSL2)

## Related

- #399 — \`dist/index.js\` missing (doctor false negative). Section C of this issue extends the scope to \`dist/core/onnx-embedder.js\` + \`dist/core/rvf-wrapper.js\`.
- #400 — \`ruvector demo\` broken across all 4 modes. The \`--basic\` and \`--gnn\` failures share root causes A and B respectively in this issue.
- #401 — \`optimize\` crashes (missing \`src/optimizer/\`); \`router\` references wrong package name. Same release-hygiene class.

**Comment by ruvnet** [comment]
Excellent triage — splitting it into A/B/C buckets made the right scope cuts very clear.

**§C (more missing `dist/` paths) — fully fixed in #403** (commit ceee9fd), shipping in `ruvector@0.2.24`. Same root cause as #399: the published tarball had no `dist/` at all. The new `prepublishOnly` gate (`scripts/verify-dist.js`) now scans `bin/cli.js` for every `require('../dist/...')` site and asserts each one ships. After 0.2.24 lands, `embed text`, `rvf status`, `rvf segments`, `rvf create` should all work.

**§A (`VectorDB` API drift) and §B (GNN/attention typed-array failures) — deferred from this PR.** These need a real audit of the `@ruvector/core@0.1.31` and `@ruvector/gnn` native binding surfaces against what the CLI assumes. The CLI calls `db.insertBatch(...)` and `db.insert(...)` (which are missing or renamed), and pipes plain `number[]` into napi-rs typed-array slots (which need `Float32Array`). Both are tractable but require correlating the Rust binding's exported names + arg shapes against every CLI call site, which is a separate piece of work.

Will open a tracking issue for "@ruvector/core CLI binding-surface audit" so §A/§B don't get lost. Your CI suggestion (CRUD round-trip + GNN/attention shape tests on a fresh install) is the right gate — going to wire that into the workspace-CI ladder alongside the audit.

For now: `0.2.24` unblocks the entire `embed`/`rvf` family + `doctor` + `optimize` + `router` help. CRUD/GNN/attention remain blocked until the binding audit lands.

**Comment by ruvnet** [comment]
Following up on the §A and §B audit. CLI-side bits landed in #404 (commit 8f3f0b3), shipping in **`ruvector@0.2.25`**.

## §A — \`VectorDB\` API drift: CLI side fixed

Two distinct issues, both at the CLI level:

1. **Distance metric casing**: native `JsDistanceMetric` enum is PascalCase (`Cosine | Euclidean | DotProduct | Manhattan`), CLI passed lowercase. Added `normalizeMetric()` in `src/index.ts` that maps both casings + common aliases (`l2`, `dot`, `dotproduct`, `innerproduct`, `l1`).

2. **Demo `--basic` API mismatch**: old positional `db.insert('id', [...], {meta})` doesn't match the current single-object shape. Replaced with `await db.insert({ id, vector: new Float32Array(...), metadata })`. Verified end-to-end:

   ```
   $ node bin/cli.js demo --basic
     Searching for nearest to [0.8, 0.6, 0, 0]:
       1. vec4 (score: 0.0101)  ✓ closest to query
       2. vec1 (score: 0.2000)
       3. vec2 (score: 0.4000)
   ```

## §A — \`VectorDB\` API drift: binding-side issue identified

Beyond the CLI fixes, there's a real published-binding regression in `ruvector-core@0.1.29` (the native `.node` files behind `@ruvector/core`). Reproduced minimally:

```js
const c = require('@ruvector/core');
const d1 = new c.VectorDb({ dimensions: 4 });
await d1.insert({ id: 'a', vector: new Float32Array(4) });  // OK

const d2 = new c.VectorDb({ dimensions: 64 });               // ← ignored
await d2.insert({ id: 'b', vector: new Float32Array(64) });
// → Insert failed: Dimension mismatch: expected 4, got 64
```

The constructor's `dimensions` arg is ignored — every fresh `VectorDb` instance reports the same `expected 4`. The Rust source in this repo (`crates/ruvector-node/src/lib.rs:222-253`) shows the constructor correctly threading `options.dimensions` through `JsDbOptions → DbOptions → CoreVectorDB::new()`, with each instance owning an independent `Arc<RwLock<CoreVectorDB>>` — so the published `.node` artifact is stale, not the source.

This is why the demo `--benchmark` is pinned to `dim=4` for now (it works reliably there). Once the binding is rebuilt from current source, `dim` scales freely.

## §B — GNN/attention typed-array failures

**Attention compute (\`Failed to convert napi value Undefined into rust type u32\`)**: root cause was wrong API surface. The CLI invoked `attn.forward([query], keys, values)` but every current `@ruvector/attention` class exposes `compute(query, keys, values)` instead — `forward` doesn't exist. Plus `query` must be a flat `Float32Array`, not `[query]`. Replaced all five branches:

```
$ node bin/cli.js attention compute -q \"[1,0,0,0]\" -k keys.json -t dot
  ✔ Attention computed (dot)
  Output: [0.6225, 0.3775, 0, 0...]
```

**GNN typed-array (\`Get TypedArray info failed\`)**: CLI fixed (all `number[]` → `Float32Array`). But there's a separate binding-side regression in `@ruvector/gnn@0.1.25`: every method throws `Given napi value is not an array`, regardless of input. Reproduced with both `Array<Float32Array>` and `number[][]` and even after `gnn.init()`:

```js
const gnn = require('@ruvector/gnn');
const q = new Float32Array([1, 2, 3, 4]);
const c = [new Float32Array([1, 0, 0, 0])];
gnn.differentiableSearch(q, c, 1, 1.0);
// → Given napi value is not an array
```

Same shape with `RuvectorLayer.forward()`, `TensorCompress.compress()`, `hierarchicalForward()` — all throw. Constructors work; methods don't.

The CLI now detects this error pattern and surfaces a pointer instead of a confusing stack trace:

```
$ node bin/cli.js demo --gnn
  GNN demo failed: Given napi value is not an array
  Note: this is a known regression in the @ruvector/gnn native binding,
  not in the CLI. Tracking at:
    https://github.com/ruvnet/ruvector/issues/402
```

## §C — \`dist/\` paths missing

Already fully resolved by the structural fix in #403 (\`ruvector@0.2.24\`).

---

## Summary

| Bucket | Status |
|---|---|
| §A CLI-side (API shape, metric casing) | ✓ Fixed in 0.2.25 |
| §A binding-side (\`dimensions\` arg ignored) | ⏳ Needs rebuild of `ruvector-core` from current Rust source |
| §B CLI-side (typed-array, wrong method names) | ✓ Fixed in 0.2.25 |
| §B binding-side (\`@ruvector/gnn\` methods all throw) | ⏳ Needs rebuild of `@ruvector/gnn` from current Rust source |
| §C `dist/` paths | ✓ Fixed in 0.2.24 (#403) |

Both binding rebuilds are the right next step — the in-tree Rust source compiles and runs cleanly; only the published artifacts have the regression. I'll open follow-up issues to track the rebuilds.

**Comment by ruvnet** [comment]
**`ruvector@0.2.25` is now published to npm.** Validated end-to-end against a fresh global install:

```
$ npm install -g ruvector@0.2.25 @ruvector/core @ruvector/gnn @ruvector/graph-node @ruvector/attention
$ ruvector doctor
  ✓ Native binding working (native)         ← was the false negative in #399
  ✓ All checks passed!

$ ruvector demo --basic
  Searching for nearest to [0.8, 0.6, 0, 0]:
    1. vec4 (score: 0.0101)                  ← real top-result, not crash
    2. vec1 (score: 0.2000)
    3. vec2 (score: 0.4000)

$ ruvector demo --gnn
  Top 3 results:
    1. Index 3 (attention: 0.2555)            ← actually works on fresh install
    2. Index 0 (attention: 0.2521)
    3. Index 2 (attention: 0.2510)

$ ruvector demo --graph
  ✓ Created nodes: Alice (alice), Bob (bob)
  ✓ Created edge Alice -[:KNOWS]-> Bob

$ ruvector demo --benchmark
  ✓ Inserted 1000 vectors in 126ms (0.13ms/vec)
  ✓ 100× top-10 search in 51ms (0.51ms/query)

$ ruvector optimize --list
  ruvector optimize: not yet shipped in this release.    ← clean exit, not crash
  ...track at .../issues/401

$ ruvector router --info
  npm package:  npm install @ruvector/router            ← correct package now
  Rust crate:   cargo add ruvector-router-core

$ ruvector attention compute -q "[1,0,0,0]" -k keys.json -t dot
  Output: [0.6225, 0.3775, 0, 0...]                     ← real attention output
```

Side note on the binding side: re-testing `@ruvector/gnn@0.1.25` and `ruvector-core@0.1.29` against a clean `/tmp` install today, **both work end-to-end**. The "Given napi value is not an array" and "expected 4, got 64" errors I diagnosed earlier in #402 reproduced against my local stale `node_modules` cache, not against fresh-from-npm artifacts. So the binding-side rebuild concern was wrong — the published bindings are fine; only the CLI on top of them was drifting. Closing this from a CLI-side perspective.

**Comment by ronmikailov** [comment]
thank you great repo

**Comment by ruvnet** [comment]
Closing — all three sub-buckets (§A, §B, §C) are addressed in `ruvector@0.2.25` (now live on npm) and validated against a fresh global install. Recap from the validation run:

- **§A `VectorDB` API drift** — fixed in #404. `VectorDBWrapper` now normalizes the distance metric (`'cosine'` → `'Cosine'`) and accepts both `metric` and `distanceMetric` constructor aliases. The `insertBatch is not a function` errors traced back to the missing `dist/` from §C; once `dist/` ships, the wrapper exposes the correct surface.
- **§B GNN/attention typed-array failures** — fixed in #404. `attention compute` was calling a non-existent `forward()` method; replaced with `compute()` per the actual binding surface, plus `Float32Array` conversion at every call site. Verified with `attention compute -t dot` returning `[0.6225, 0.3775, 0, 0]`.
- **§C missing `dist/` paths** — fixed in #403 via `scripts/verify-dist.js` wired into `prepublishOnly`, so the artifact-incomplete class of bug fails publish loudly.

The two binding-side regressions I'd flagged in earlier comments (`@ruvector/gnn@0.1.25` "not an array" / `ruvector-core@0.1.29` "expected 4") **don't reproduce against fresh-from-npm artifacts** — both were stale-`node_modules` artifacts on my end, not actual published binding bugs. Tested with a clean `/tmp` install today: `differentiableSearch` returns top-k correctly and `VectorDb({ dimensions: 64 })` accepts 64-dim vectors as expected.

Reopen if anything regresses on a clean install of `ruvector@0.2.25` — and thanks again for the precise repro on the original report; the §A/§B/§C split made the fixes very targeted.
