### ISSUE TITLE
bug(sona): @ruvector/sona@0.1.5 binary out of sync with ruvector@0.2.18 wrapper — getStats() and saveState() crash

### ISSUE THREAD

**Issue by dmoellenbeck** [ruvnet/RuVector#301]
## Bug Description

`ruvector@0.2.18` ships an updated `sona-wrapper.js` that calls `saveState()`,
`loadState()`, and expects JSON from `getStats()`. However, the native binary
package `@ruvector/sona@0.1.5` was not rebuilt — it predates PR #284 and is
missing the new NAPI exports.

### Symptoms

**1. `getStats()` — JSON.parse fails**

The v0.1.5 native binary returns Rust `Debug` format instead of JSON:

```
CoordinatorStats { trajectories_buffered: 5, trajectories_dropped: 0, ... }
```

The wrapper does `JSON.parse(statsJson)` → crash:

```
SyntaxError: Unexpected token 'C', "Coordinato"... is not valid JSON
```

The camelCase mapping fix from PR #284 never executes because parsing fails first.

**2. `saveState()` / `loadState()` — native methods missing**

The wrapper calls `this._native.saveState()`, but the v0.1.5 binary doesn't
export these methods:

```
TypeError: this._native.saveState is not a function
```

The `@ruvector/sona@0.1.5` type declarations (`index.d.ts`) also don't include
`saveState`/`loadState`, confirming `napi build` was not re-run.

## Root Cause

**Version mismatch between packages:**

| Package | Version | Has PR #284 fixes? |
|---------|---------|-------------------|
| `ruvector` (JS wrapper) | 0.2.18 | Yes (sona-wrapper.js updated) |
| `@ruvector/sona` (NAPI binary) | 0.1.5 | **No** (binary not rebuilt) |
| `@ruvector/sona-darwin-arm64` (native .node) | 0.1.5 | **No** |

The Rust source in `crates/sona/src/napi.rs` has the correct implementations
(`save_state`, `load_state`, `serde_json::to_string` for `get_stats`), but
the cross-compilation pipeline was not triggered before publishing `ruvector@0.2.18`.

## Environment

- **ruvector**: 0.2.18 (npm)
- **@ruvector/sona**: 0.1.5 (npm)
- **Node.js**: v25.7.0
- **Platform**: macOS Apple Silicon (darwin-arm64)

## To Reproduce

```javascript
const { SonaEngine } = require('ruvector');
const sona = new SonaEngine(16);

for (let i = 0; i < 5; i++) {
  const tid = sona.beginTrajectory(new Array(16).fill(Math.random()));
  sona.addStep(tid, new Array(16).fill(0.5), new Array(16).fill(0.1), 0.8);
  sona.endTrajectory(tid, 0.9);
}

// Both crash:
try { sona.getStats(); } catch(e) { console.log(e.message); }
// "Unexpected token 'C', "Coordinato"... is not valid JSON"

try { sona.saveState(); } catch(e) { console.log(e.message); }
// "this._native.saveState is not a function"
```

## Suggested Fix

1. **Rebuild native binaries**: Run `napi build` for all platforms, publish
   `@ruvector/sona@0.1.6+` with the current `napi.rs` code
2. **Ensure `CoordinatorStats` derives `Serialize`** so `serde_json::to_string`
   produces valid JSON (vs. `Debug` fallback)
3. **Optional**: Add defensive `try/catch` in `sona-wrapper.js` `getStats()` for
   backwards compatibility with older binaries

## What works in v0.2.18

| Feature | Status |
|---------|--------|
| `beginTrajectory` / `addStep` / `endTrajectory` | ✓ |
| `forceLearn()` | ✓ (132 trajectories → 2 patterns) |
| `findPatterns()` | ✓ |
| `getStats()` | ✗ JSON parse crash |
| `saveState()` | ✗ native method missing |
| `loadState()` | ✗ native method missing |

Thank you @ruvnet for the work on v0.5.0-dragnes! This looks like a CI/CD sequencing
issue — the JS wrapper was published before the native binary rebuild completed.

**Comment by ruvnet** [comment]
Fixed: @ruvector/sona@0.1.6 is now published on npm with the correct NAPI exports (save_state, load_state, JSON from get_stats). The Rust source in crates/sona/src/napi.rs already had the fixes from PR #284.
